### ISSUE TITLE
Algorithm Not Allowed on PHP 7.4 since version 0.2.7

### ISSUE THREAD

**Issue by gimmer** [patrickbussmann/oauth2-apple#34] opened 2022-05-03 19:59 UTC
Previously on 0.2.6, we were authorizing with apple without difficulty on a PHP 7.4 setup. 
Moving to 0.2.7 breaks our authorization, getting "Algorithm Not Allowed" on all attempts.

It appears that $keyOrKeyArray is coming into getKeyMaterialAndAlgorithm as resource of type (OpenSSL key), and is hitting the first if and bailing with no algorithm. 

I think JWT is doing the casting.

**Comment by patrickbussmann** [comment] 2022-05-03 20:20
Very interesting. I'll add a unit test for that to ensure that this not breaks anything.
Do you have example which is not working? Because i think my example on readme is working.
Maybe your system setup (phpinfo)? You can mail me (info@bussmann-it.de)

**Comment by tjveldhuizen** [comment] 2022-05-09 10:58
We have the same effect on PHP 8.1. I have not been able yet to investigate thoroughly (because my local setup is not compatible with the Apple requirements like not using .localhost etc).

**Comment by patrickbussmann** [comment] 2022-05-09 22:13
Yes you're right @tjveldhuizen.
I found out that I missed the unit tests with the v5 and v6 so that the tests are only for v6.
Now I added the versions to the matrix so that we'll not have this issue again.
https://github.com/patrickbussmann/oauth2-apple/actions/runs/2297085423

This is fixed now. Please inform me if not. 👍

**Closed by patrickbussmann** 2022-05-09 22:13 UTC

**Comment by tjveldhuizen** [comment] 2022-05-09 22:31
Thanks for the rapid fix! I'll test it.

Is it by design that the new tags (0.2.7 en 0.2.8) are not on the releases page?

**Comment by tjveldhuizen** [comment] 2022-05-09 22:59
With the 0.2.8-version, my login functions for Apple are working again. Thanks!
